name: 'Rebase epic'
description: 'Rebases [Epic] pull requests when a commit is pushed'
author: 'Shuttlerock'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  repo-token:
    description: 'Github access token'
  write-token:
    description: "Github access token with write access - added manually to organization secrets because the default token provided by actions doesn't have enough permissions"
