name: 'Pull request was reviewed'
description: 'Add label passed-review'
author: 'Shuttlerock'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  credentials-api-prefix:
    description: 'The prefix of the REST API method to fetch user credentials'
  credentials-api-secret:
    description: 'The shared signing secret used to fetch user credentials'
  organization-name:
    description: 'The name of the Github organization'
  repo-token:
    description: 'Github access token'
  slack-token:
    description: 'Slack access token with write access'
  write-token:
    description: 'Github access token with write access'
