defaults: &defaults
  working_directory: ~/actions
  docker:
    - image: circleci/node:12.13-browsers
      auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  environment:
    ENV: test

version: 2.1

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/actions

  yarn_dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          name: "Restore checkout cache"
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: "Restore yarn cache"
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: "Save yarn cache"
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/actions/node_modules

  compile:
    <<: *defaults
    steps:
      - restore_cache:
          name: "Restore checkout cache"
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: "Restore yarn cache"
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run:
          name: Production build to test against
          command: |
            rm -rf node_modules/.cache
            yarn clean
            yarn build
            yarn package

  jest:
    <<: *defaults
    resource_class: large # Work around out-of-memory errors.
    steps:
      - restore_cache:
          name: "Restore checkout cache"
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: "Restore yarn cache"
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn test

  lint:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn lint

  format:
    <<: *defaults
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn format-check

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          context:
            - docker-hub-creds
      - yarn_dependencies:
          context:
            - docker-hub-creds
          requires:
            - checkout_code
      - compile:
          context:
            - docker-hub-creds
          requires:
            - yarn_dependencies
      - jest:
          context:
            - docker-hub-creds
          requires:
            - yarn_dependencies
      - lint:
          context:
            - docker-hub-creds
          requires:
            - yarn_dependencies
      - format:
          context:
            - docker-hub-creds
          requires:
            - yarn_dependencies
