name: 'Pull request converted to draft'
description: 'Organizes project stories after a pull request is marked as converted to draft'
author: 'Shuttlerock'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  jira-email:
    description: 'Email address of the Jira user whose access token we are using'
  jira-host:
    description: 'The domain where Jira is hosted'
  jira-token:
    description: 'Jira access token'
  organization-name:
    description: 'The name of the Github organization'
  repo-token:
    description: 'Github access token'
  write-token:
    description: 'Github access token with write access'
