name: 'Trigger Action'
description: 'Trigger an action via a HTTP request'
author: 'Shuttlerock'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  jira-token:
    description: 'Jira access token'
  repo-token:
    description: 'Github access token'
  write-token:
    description: 'Github access token with write access'
