name: 'Trigger Action'
on:
  workflow_dispatch:
    inputs:
      event:
        description: 'The name of the event to trigger'
        required:    true
      param:
        description: 'A string containing a parameter to pass when triggering the event'
        required:    false

jobs:
  trigger_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/trigger-action
        with:
          jira-token:  ${{ secrets.JIRA_TOKEN }}
          repo-token:  ${{ secrets.GITHUB_TOKEN }}
          write-token: ${{ secrets.ACTIONS_WRITE_TOKEN }}
